### ISSUE TITLE
AutoAttack does not run

### ISSUE THREAD

**Issue by mzweilin** [IntelLabs/MART#79]
```console
$ python -m mart experiment=CIFAR10_RobustBench trainer=gpu fit=false +trainer.limit_test_batches=1 +attack@model.modules.input_adv_test=classification_autoattack

[2023-02-16 11:35:14,513][mart.utils.utils][ERROR] -
Traceback (most recent call last):
  File "/home/weilinxu/coder/MART/.venv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'adversary'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/weilinxu/coder/MART/mart/utils/utils.py", line 54, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/weilinxu/coder/MART/mart/tasks/lightning.py", line 39, in lightning
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/home/weilinxu/coder/MART/.venv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/home/weilinxu/coder/MART/.venv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 334, in instantiate_node
    value = instantiate_node(
  File "/home/weilinxu/coder/MART/.venv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 349, in instantiate_node
    dict_items[key] = instantiate_node(
  File "/home/weilinxu/coder/MART/.venv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 339, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/weilinxu/coder/MART/.venv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'mart.attack.adversary_wrapper.NormalizedAdversaryAdapter':
TypeError("__init__() got an unexpected keyword argument 'adversary'")
full_key: model.modules.input_adv_test
[2023-02-16 11:35:14,514][mart.utils.utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=CIFAR10_RobustBench', 'trainer=gpu', 'fit=false', '+trainer.limit_test_batches=1', '+attack@model.modules.input_adv_test=classification_autoattack']
Error in call to target 'mart.attack.adversary_wrapper.NormalizedAdversaryAdapter':
TypeError("__init__() got an unexpected keyword argument 'adversary'")
full_key: model.modules.input_adv_test

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by dxoigmn** [comment]
Smells like we're missing a test...
